name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          working-directory: ${{ github.workspace }}/api
      - run: npm install
        working-directory: ${{ github.workspace }}/api
      - run: npm run build --if-present
        working-directory: ${{ github.workspace }}/api
        
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          working-directory: ${{ github.workspace }}/front-end
      - run: npm install
        working-directory: ${{ github.workspace }}/front-end
      - run: npm run build --if-present
        working-directory: ${{ github.workspace }}/front-end
